require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context"]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    - benchmark/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Max: 2
